### ISSUE TITLE
Add Polish language

### ISSUE THREAD

**Issue by 3limssmile** [lorenzovngl/FoodExpirationDates#148] opened 2024-04-22 20:58 UTC
I can translate the application into Polish

**Comment by 3limssmile** [comment] 2024-04-22 21:05
I will most likely send the translation tomorrow

**Comment by 3limssmile** [comment] 2024-04-22 21:05
I will most likely send the translation tomorrow

**Comment by lorenzovngl** [comment] 2024-04-24 17:48
Please do not close an issue that has a pull request linked, because the issue is intended to be solved when the pull request is merged.

**Closed** 2024-04-27 09:21 UTC
